## Extracting data with the Foursquare API

In [44]:
# Dicas

In [4]:
import pandas 
import requests

In [5]:
CLIENT_ID = 'P5MNEPLK4OXEDGPBP45SWSLTU1TY4R1DU4ZGMFBBOZCP23MO' # your Foursquare ID
CLIENT_SECRET = '3UTVUFOEVCRFZU5RGBMOSR4AFQG4BB4XXVN0P1NQMQNEFK2H' # your Foursquare Secret
ACCESS_TOKEN = "L5FWYDVVHZXJ4GKNOAD45X22X5MVYZJIFJHE1YJXFGDFB4YN" # your FourSquare Access Token
VERSION = '20180604'
print('Your credentails:')
print('CLIENT_ID: ' + CLIENT_ID)
print('CLIENT_SECRET:' + CLIENT_SECRET)

Your credentails:
CLIENT_ID: P5MNEPLK4OXEDGPBP45SWSLTU1TY4R1DU4ZGMFBBOZCP23MO
CLIENT_SECRET:3UTVUFOEVCRFZU5RGBMOSR4AFQG4BB4XXVN0P1NQMQNEFK2H

# Para categorias

In [6]:
url = 'https://api.foursquare.com/v2/venues/categories?&client_id={}&client_secret={}&v={}'.format(
    CLIENT_ID, 
    CLIENT_SECRET, 
    VERSION)
category_results = requests.get(url).json()

In [7]:
category_list = category_results['response']['categories']
len(category_list)

10

In [8]:
for data in category_list:
    print(data['id'], data['name'])

4d4b7104d754a06370d81259 Arts & Entertainment
4d4b7105d754a06372d81259 College & University
4d4b7105d754a06373d81259 Event
4d4b7105d754a06374d81259 Food
4d4b7105d754a06376d81259 Nightlife Spot
4d4b7105d754a06377d81259 Outdoors & Recreation
4d4b7105d754a06375d81259 Professional & Other Places
4e67e38e036454776db1fb3a Residence
4d4b7105d754a06378d81259 Shop & Service
4d4b7105d754a06379d81259 Travel & Transport

In [23]:
#category_results['response']['categories']

In [11]:
# function to flatten a 'parent_id' category, returns all categories if checkParentID = False

def flatten_Hierarchy(category_list, checkParentID, category_dict, parent_id = ''):
    
    for data in category_list:
        
        if checkParentID == True and data['id'] == parent_id:
            category_dict[data['id']] = data['name']
            flatten_Hierarchy(category_list = data['categories'], checkParentID = False, category_dict = category_dict)
        
        elif checkParentID == False:
            category_dict[data['id']] = data['name']
            if len(data['categories']) != 0:
                flatten_Hierarchy(category_list = data['categories'], checkParentID = False, category_dict = category_dict)
    
    return category_dict

In [22]:
# this function takes the parent ID and returns 'name' and 'id' of all the sub-categories

category_dict = flatten_Hierarchy(category_list, checkParentID=True, category_dict = {}, parent_id = '4d4b7105d754a06378d81259')
#category_dict

### Get the neighborhood's name.

In [21]:
import pandas as pd

manhattan_data=pd.read_csv("manhattan.csv")

manhattan_data.loc[[0]]

   Unnamed: 0    Borough Neighborhood   Latitude  Longitude
0           0  Manhattan  Marble Hill  40.876551  -73.91066

In [ ]:
4bf58dd8d48988d110951735'

In [24]:
LIMIT = 1 # limit of number of venues returned by Foursquare API
neighborhood_latitude = 40.876551
neighborhood_longitude=-73.91066
radius = 500 # define radius
categoryId = '4bf58dd8d48988d110951735' # category ID for "Food"

# create URL

url = 'https://api.foursquare.com/v2/venues/search?&client_id={}&client_secret={}&v={}&ll={},{}&radius={}&categoryId={}&limit={}'.format(
    CLIENT_ID, 
    CLIENT_SECRET, 
    VERSION, 
    neighborhood_latitude, 
    neighborhood_longitude, 
    radius,
    categoryId,
    LIMIT)
url # display URL

'https://api.foursquare.com/v2/venues/search?&client_id=P5MNEPLK4OXEDGPBP45SWSLTU1TY4R1DU4ZGMFBBOZCP23MO&client_secret=3UTVUFOEVCRFZU5RGBMOSR4AFQG4BB4XXVN0P1NQMQNEFK2H&v=20180604&ll=40.876551,-73.91066&radius=500&categoryId=4bf58dd8d48988d110951735&limit=1'

In [26]:
results = requests.get(url).json()
results['response']['venues']

[{'id': '512901b5e4b0ce6661fefdc1',
  'name': 'Marble Hill Unisex',
  'location': {'lat': 40.87738929799393,
   'lng': -73.90928264388714,
   'labeledLatLngs': [{'label': 'display',
     'lat': 40.87738929799393,
     'lng': -73.90928264388714}],
   'distance': 148,
   'postalCode': '10463',
   'cc': 'US',
   'city': 'Bronx',
   'state': 'NY',
   'country': 'United States',
   'formattedAddress': ['Bronx, NY 10463', 'United States']},
  'categories': [{'id': '4bf58dd8d48988d110951735',
    'name': 'Salon / Barbershop',
    'pluralName': 'Salons / Barbershops',
    'shortName': 'Salon / Barbershop',
    'icon': {'prefix': 'https://ss3.4sqi.net/img/categories_v2/shops/salon_barber_',
     'suffix': '.png'},
    'primary': True}],
  'referralId': 'v-1618854111',
  'hasPerk': False}]

In [27]:
categoryId_list = []
for key, value in category_dict.items():
    categoryId_list.append(key)
categoryId = ','.join(categoryId_list)

In [28]:
def getNearbyFood(names, latitudes, longitudes, radius=1000, LIMIT=500):
    not_found = 0
    print('***Start ', end='')
    venues_list=[]
    for name, lat, lng in zip(names, latitudes, longitudes):
        print(' .', end='')
            
        # create the API request URL
        url = 'https://api.foursquare.com/v2/venues/search?&client_id={}&client_secret={}&v={}&ll={},{}&radius={}&categoryId={}&limit={}'.format(
            CLIENT_ID, 
            CLIENT_SECRET, 
            VERSION, 
            lat, 
            lng, 
            radius,
            "4d4b7105d754a06374d81259", # "Food" category id
            LIMIT)
            
        try:
            # make the GET request
            results = requests.get(url).json()['response']['venues']
            
            # return only relevant information for each nearby venue
            venues_list.append([(
                name, 
                lat, 
                lng, 
                v['name'], 
                v['location']['lat'], 
                v['location']['lng'],  
                v['categories'][0]['name']) for v in results])
        except:
            not_found += 1


    nearby_venues = pd.DataFrame([item for venue_list in venues_list for item in venue_list])
    nearby_venues.columns = ['Neighborhood', 
                  'Neighborhood Latitude', 
                  'Neighborhood Longitude', 
                  'Venue', 
                  'Venue Latitude', 
                  'Venue Longitude', 
                  'Venue Category']
    print("\nDone*** with {} venues with incompelete information.".format(not_found))
    return(nearby_venues)

In [30]:
import pickle # to serialize and deserialize a Python object structure
try:
    with open('nyc_food_venues.pkl', 'rb') as f:
        nyc_venues = pickle.load(f)
    print("---Dataframe Existed and Deserialized---")
except:
    nyc_venues = getNearbyFood(names=manhattan_data['Neighborhood'],
                                        latitudes=manhattan_data['Latitude'],
                                        longitudes=manhattan_data['Longitude']
                                       )
    with open('nyc_food_venues.pkl', 'wb') as f:
        pickle.dump(nyc_venues, f)
    print("---Dataframe Created and Serialized---")

***Start  . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .
Done*** with 0 venues with incompelete information.
---Dataframe Created and Serialized---

In [4]:
url = 'https://api.foursquare.com/v2/venues/search?client_id={}&client_secret={}&ll={},{}&oauth_token={}&v={}&query={}&radius={}&limit={}'.format(CLIENT_ID, CLIENT_SECRET, latitude, longitude,ACCESS_TOKEN, VERSION, search_query, radius, LIMIT)
url

'https://api.foursquare.com/v2/venues/search?client_id=P5MNEPLK4OXEDGPBP45SWSLTU1TY4R1DU4ZGMFBBOZCP23MO&client_secret=3UTVUFOEVCRFZU5RGBMOSR4AFQG4BB4XXVN0P1NQMQNEFK2H&ll=40.7601085,-73.97816329087175&oauth_token=L5FWYDVVHZXJ4GKNOAD45X22X5MVYZJIFJHE1YJXFGDFB4YN&v=20180604&query=Drybar&radius=10000&limit=100'

In [5]:
import requests

results_1 = requests.get(url).json()

In [6]:
from pandas.io.json import json_normalize 
import warnings
warnings.filterwarnings('ignore')

venues = results_1['response']['venues']

dframe = json_normalize(venues)

dframe

,id,name,categories,referralId,hasPerk,location.address,location.crossStreet,location.lat,location.lng,location.labeledLatLngs,...,location.country,location.formattedAddress,venuePage.id,location.neighborhood,delivery.id,delivery.url,delivery.provider.name,delivery.provider.icon.prefix,delivery.provider.icon.sizes,delivery.provider.icon.name
0,5345ddce498e374167fa7173,DryBar,"[{'id': '4bf58dd8d48988d110951735', 'name': 'S...",v-1618826511,False,141 E 56th St,56th Street And Lexington Avenue,40.760087,-73.969126,"[{'label': 'display', 'lat': 40.76008684544023...",...,United States,[141 E 56th St (56th Street And Lexington Aven...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,4f2064f8e4b0a00cf1d3c3c1,Drybar,"[{'id': '4bf58dd8d48988d110951735', 'name': 'S...",v-1618826511,False,119 W 56th St,btwn 6th & 7th Ave,40.764110,-73.978769,"[{'label': 'display', 'lat': 40.76410996501346...",...,United States,"[119 W 56th St (btwn 6th & 7th Ave), New York,...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,558e9564498e4c9557996706,Drybar Bryant Park,"[{'id': '4bf58dd8d48988d110951735', 'name': 'S...",v-1618826511,False,19 E 39th St,Madison Avenue,40.751130,-73.980992,"[{'label': 'display', 'lat': 40.75113006507257...",...,United States,"[19 E 39th St (Madison Avenue), New York, NY 1...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,4e6f679dae604d1b459a5154,DryBar,"[{'id': '4bf58dd8d48988d110951735', 'name': 'S...",v-1618826511,False,4 W 16th St,at 5th Ave,40.737554,-73.993193,"[{'label': 'display', 'lat': 40.73755376258029...",...,United States,"[4 W 16th St (at 5th Ave), New York, NY 10011,...",77545546,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,5db77e4d10a19d000875e753,Drybar,"[{'id': '54541900498ea6ccd0202697', 'name': 'H...",v-1618826511,False,NaN,NaN,40.766853,-73.981578,"[{'label': 'display', 'lat': 40.766853, 'lng':...",...,United States,"[New York, NY 10019, United States]",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,50df63efe4b0454c5e8f655d,Drybar,"[{'id': '4bf58dd8d48988d110951735', 'name': 'S...",v-1618826511,False,180 W Broadway,NaN,40.718100,-74.007092,"[{'label': 'display', 'lat': 40.71809983636473...",...,United States,"[180 W Broadway, New York, NY 10013, United St...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,59a4d46e61f0705add6bacf6,Drybar,"[{'id': '4bf58dd8d48988d110951735', 'name': 'S...",v-1618826511,False,300 E 64th St,2nd Avenue,40.763686,-73.962035,"[{'label': 'display', 'lat': 40.76368609352094...",...,United States,"[300 E 64th St (2nd Avenue), New York, NY 1006...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,5085a82ce4b06b2e3c6b644b,Dry Bar,"[{'id': '4bf58dd8d48988d110951735', 'name': 'S...",v-1618826511,False,222 E 34th St,btwn 2nd & 3rd Ave,40.745172,-73.976737,"[{'label': 'display', 'lat': 40.74517240883449...",...,United States,"[222 E 34th St (btwn 2nd & 3rd Ave), New York,...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,5085a8b5e4b0ca321fdcea32,Dry Bar,"[{'id': '4bf58dd8d48988d110951735', 'name': 'S...",v-1618826511,False,209 E 76th St,3rd Ave.,40.772205,-73.958315,"[{'label': 'display', 'lat': 40.77220496421525...",...,United States,"[209 E 76th St (3rd Ave.), New York, NY 10021,...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,565da01f498ef6985cb9a345,Drybar Soho in Bloomingdale's,"[{'id': '54541900498ea6ccd0202697', 'name': 'H...",v-1618826511,False,44 Crosby St,NaN,40.722060,-73.998890,"[{'label': 'display', 'lat': 40.72205973261088...",...,United States,"[44 Crosby St, New York, NY 10012, United States]",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,54ae7536498e4611855629f5,Drybar UWS,"[{'id': '54541900498ea6ccd0202697', 'name': 'H...",v-1618826511,False,69 W 71st at,Columbus,40.776643,-73.978950,"[{'label': 'display', 'lat': 40.77664331302199...",...,United States,"[69 W 71st at (Columbus), New York, NY, United...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,573ef3fd498e246fea9ae4b5,Dry Bar Hell's Kitchen,"[{'id': '4bf58dd8d48988d110951735', 'name': 'S...",v-1618826511,False,492 W 42nd Street,10th Avenue,40.759477,-73.995454,"[{'label': 'display', 'lat': 40.75947725252716...",...,United States,"[492 W 42nd Street (10th Avenue), New York, NY...",NaN,Hell's Kitchen,1136990,https://www.seamless.com/menu/hells-kitchen-go...,seamless,https://fastly.4sqi.net/img/general/cap/,"[40, 50]",/delivery_provider_seamless_20180129.png
12,581df4b5b04e9861eb58bf73,Drybar Lower East Side,"[{'id': '54541900498ea6ccd0202697', 'name': 'H...",v-1618826511,False,179 Ludlow St,NaN,40.721952,-73.987415,"[{'label': 'display', 'lat': 40.72195188598967...",...,United States,"[179 Ludlow St, New York, NY 10002, United Sta...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,5293c092498efb087b95ea2c,Drybar Murray Hill,"[{'id': '4bf58dd8d48988d110951735', 'name': 'S...",v-1618826511,False,NaN,NaN,40.745144,-73.979407,"[{'label': 'display', 'lat': 40.74514398442719...",...,United States,"[New York, NY, United States]",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,57732792498edf5509c6c020,oneblowdrybar at Macy’s Herald Square,"[{'id': '54541900498ea6ccd0202697', 'name': 'H...",v-1618826511,False,"One Below, 151 West 34th Street",West 35th Street,40.750589,-73.988242,"[{'label': 'display', 'lat': 40.75058941088087...",...,United States,"[One Below, 151 West 34th Street (West 35th St...",NaN,"Garment District, New York, NY",NaN,NaN,NaN,NaN,NaN,NaN
15,5b7d6c786fd626002c394614,Drybar,"[{'id': '4bf58dd8d48988d110951735', 'name': 'S...",v-1618826511,False,1495 3rd Ave,NaN,40.777626,-73.954491,"[{'label': 'display', 'lat': 40.77762603759765...",...,United States,"[1495 3rd Ave, New York, NY 10028, United States]",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16,5a983849a5a3156b15012ff4,Drybar,"[{'id': '4bf58dd8d48988d110951735', 'name': 'S...",v-1618826511,False,243 W 99th St,NaN,40.796906,-73.970680,"[{'label': 'display', 'lat': 40.79690551757812...",...,United States,"[243 W 99th St, New York, NY 10025, United Sta...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17,5675b3fa498eafd413130732,DryBar,"[{'id': '54541900498ea6ccd0202697', 'name': 'H...",v-1618826511,False,Brookfield Place,NaN,40.713795,-74.015328,"[{'label': 'display', 'lat': 40.71379518038771...",...,United States,"[Brookfield Place, New York, NY, United States]",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18,5628e8f7498e5a2719912fb0,Drybar Greenwich Village,"[{'id': '4bf58dd8d48988d110951735', 'name': 'S...",v-1618826511,False,60 E 10th St,NaN,40.731890,-73.991762,"[{'label': 'display', 'lat': 40.73189045102772...",...,United States,"[60 E 10th St, New York, NY 10003, United States]",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19,54943a62498eff4bb43d26b0,DryBar Meatpacking,"[{'id': '54541900498ea6ccd0202697', 'name': 'H...",v-1618826511,False,317 W 13th St,NaN,40.739431,-74.003996,"[{'label': 'display', 'lat': 40.73943055057877...",...,United States,"[317 W 13th St, New York, NY 10014, United Sta...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20,5b474e2c10b30300247c8a49,Drybar Hoboken,"[{'id': '4bf58dd8d48988d110951735', 'name': 'S...",v-1618826511,False,218 Washington St,2nd Street,40.739429,-74.030708,"[{'label': 'entrance', 'lat': 40.739398, 'lng'...",...,United States,"[218 Washington St (2nd Street), Hoboken, NJ 0...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
21,514b8985e4b080852ac00c85,#Intelfashion at Drybar!,"[{'id': '4bf58dd8d48988d110951735', 'name': 'S...",v-1618826511,False,NaN,NaN,40.737623,-73.993772,"[{'label': 'display', 'lat': 40.73762252204638...",...,United States,"[New York, NY, United States]",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
22,57d34283498e5a4993a2eff7,Drybar Boerum Hill,"[{'id': '54541900498ea6ccd0202697', 'name': 'H...",v-1618826511,False,215 Pacific St,Court Street,40.689025,-73.992177,"[{'label': 'display', 'lat': 40.68902542813316...",...,United States,"[215 Pacific St (Court Street), Brooklyn, NY 1...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
23,58efd26867af3a2c5ae21e34,Blo Blow Dry Bar,"[{'id': '54541900498ea6ccd0202697', 'name': 'H...",v-1618826511,False,113 W 10th St,NaN,40.734924,-73.999359,"[{'label': 'display', 'lat': 40.73492431640625...",...,United States,"[113 W 10th St, New York, NY 10011, United Sta...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
24,55354a66498e43895e540020,Gabriel Shimunov Hair Salon,"[{'id': '4bf58dd8d48988d110951735', 'name': 'S...",v-1618826511,False,57 W 57th St Fl 11,5th and 6th Ave.,40.764275,-73.977090,"[{'label': 'display', 'lat': 40.76427508008564...",...,United States,"[57 W 57th St Fl 11 (5th and 6th Ave.), New Yo...",126384699,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25,5740c975498e39a5c6e1e6da,Dry Bar - Hell's Kitchen,"[{'id': '4bf58dd8d48988d110951735', 'name': 'S...",v-1618826511,False,NaN,NaN,40.759324,-73.994336,"[{'label': 'display', 'lat': 40.759324, 'lng':...",...,United States,"[New York, NY, United States]",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
26,5546681f498e448ae1f7cc9d,Dry Bar,"[{'id': '54541900498ea6ccd0202697', 'name': 'H...",v-1618826511,False,69 W 71st St,NaN,40.776709,-73.978769,"[{'label': 'display', 'lat': 40.77670900000000...",...,United States,"[69 W 71st St, New York, NY 10023, United States]",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
27,51ccd28d498e8edf647e0d88,Blo Blow Dry Bar,"[{'id': '54541900498ea6ccd0202697', 'name': 'H...",v-1618826511,False,325 East 64th Street,2nd Ave.,40.763483,-73.961196,"[{'label': 'display', 'lat': 40.763483, 'lng':...",...,United States,"[325 East 64th Street (2nd Ave.), New York, NY...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
28,576ab85f498ea7d347c23267,Blo Blow Dry Bar,"[{'id': '54541900498ea6ccd0202697', 'name': 'H...",v-1618826511,False,142 East 49th Street,NaN,40.755502,-73.972220,"[{'label': 'display', 'lat': 40.755502, 'lng':...",...,United States,"[142 East 49th Street, New York, NY 10017, Uni...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
29,52ed381d498e515b85c74a27,Blo Blow Dry Bar,"[{'id': '54541900498ea6ccd0202697', 'name': 'H...",v-1618826511,False,260 East 72nd Street,2nd ave,40.768798,-73.958760,"[{'label': 'display', 'lat': 40.768798, 'lng':...",...,United States,"[260 East 72nd Street (2nd ave), New York, NY ...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
30,5a749b70e2d4aa45ead68c65,Dry Bar,"[{'id': '4bf58dd8d48988d110951735', 'name': 'S...",v-1618826511,False,243 W 99th St,NaN,40.796874,-73.970668,"[{'label': 'display', 'lat': 40.796874, 'lng':...",...,United States,"[243 W 99th St, New York, NY 10025, United Sta...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
31,536d583b11d2f3547c412a94,Blo Blow Dry Bar,"[{'id': '54541900498ea6ccd0202697', 'name': 'H...",v-1618826511,False,800 6th Avenue,btwn W 27th & W 28th St,40.745588,-73.990489,"[{'label': 'display', 'lat': 40.745588, 'lng':...",...,United States,"[800 6th Avenue (btwn W 27th & W 28th St), New...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
32,5c6892aaf709c1002cba9699,Blo Blow Dry Bar,"[{'id': '4bf58dd8d48988d110951735', 'name': 'S...",v-1618826511,False,331 E 81st St,btwn 1st & 2nd Ave,40.774260,-73.952937,"[{'label': 'display', 'lat': 40.77426, 'lng': ...",...,United States,"[331 E 81st St (btwn 1st & 2nd Ave), New York,...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
33,58e96bf99c95484a51494b3e,Dry Bar,"[{'id': '54541900498ea6ccd0202697', 'name': 'H...",v-1618826511,False,143 Kent Ave,Between N 5th and 6th,40.719419,-73.962617,"[{'label': 'display', 'lat': 40.71941946315451...",...,United States,"[143 Kent Ave (Between N 5th and 6th), New Yor...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
34,587f9a323ef0f6426ea9fed4,Blo Blow Dry Bar,"[{'id': '4bf58dd8d48988d110951735', 'name': 'S...",v-1618826511,False,460 Third Avenue,NaN,40.744437,-73.979384,"[{'label': 'display', 'lat': 40.7444371, 'lng'...",...,United States,"[460 Third Avenue, New York, NY 10016, United ...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
35,57001738cd10a426c20ea3dd,Blo Blow Dry Bar,"[{'id': '54541900498ea6ccd0202697', 'name': 'H...",v-1618826511,False,287 Amsterdam Avenue,74th,40.779733,-73.980574,"[{'label': 'display', 'lat': 40.779733, 'lng':...",...,United States,"[287 Amsterdam Avenue (74th), New York, NY 100...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
36,59cbee67a0215b7fe38355a3,oneblowdrybar (Flatiron District),"[{'id': '4bf58dd8d48988d110951735', 'name': 'S...",v-1618826511,False,"138 5th Avenue, #FL 2",NaN,40.739002,-73.991697,"[{'label': 'display', 'lat': 40.73900233881628...",...,United States,"[138 5th Avenue, #FL 2, New York, NY 10011, Un...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
37,5377f56611d245aa7ab39ce9,BDry Blow Bar,"[{'id': '4bf58dd8d48988d110951735', 'name': 'S...",v-1618826511,False,88 Leonard St,Broadway,40.717017,-74.004246,"[{'label': 'display', 'lat': 40.71701700682541...",...,United States,"[88 Leonard St (Broadway), New York, NY 10013,...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
38,514c6d1580550268cdba3537,Blow out - Boutique Beauty Bar,"[{'id': '4bf58dd8d48988d110951735', 'name': 'S...",v-1618826511,False,908 Amsterdam Ave,104th & 105th,40.799403,-73.966484,"[{'label': 'display', 'lat': 40.79940281169377...",...,United States,"[908 Amsterdam Ave (104th & 105th), New York, ...",51327690,NaN,NaN,NaN,NaN,NaN,NaN,NaN
39,5db71016e370da000860a2c6,Blo Blow Dry Bar,"[{'id': '4bf58dd8d48988d110951735', 'name': 'S...",v-1618826511,False,105 Nassau Street,NaN,40.710713,-74.007394,"[{'label': 'display', 'lat': 40.71071269999999...",...,United States,"[105 Nassau Street, New York, NY 10038, United...",569417426,NaN,NaN,NaN,NaN,NaN,NaN,NaN
40,5bb0ef40e1f0aa002c3a5bfd,Blo Blow Dry Bar,"[{'id': '4bf58dd8d48988d110951735', 'name': 'S...",v-1618826511,False,160 Morgan St,Marin Boulevard,40.720369,-74.040798,"[{'label': 'display', 'lat': 40.720369, 'lng':...",...,United States,"[160 Morgan St (Marin Boulevard), Jersey City,...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
41,5634f740498eb62fdc1f9f3e,Blown Away Blow Dry Bar,"[{'id': '4bf58dd8d48988d110951735', 'name': 'S...",v-1618826511,False,70-19 Austin St Fl 2,70th road and Austin street,40.720890,-73.846184,"[{'label': 'display', 'lat': 40.72089004516601...",...,United States,[70-19 Austin St Fl 2 (70th road and Austin st...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [43]:
df_midtown=dframe[[ "id","name"]]
df_midtown.id
lista_id=df_midtown["id"]
lista_id.tolist()
len(lista_id)

42

# Analysis

### Explore more specific data from the first Dataframe Drybar

In [35]:
print( "The fist Drybar is:", results_1["response"]["venues"][14]['id'])

The fist Drybar is: 57732792498edf5509c6c020

In [38]:
venue_id = '57732792498edf5509c6c020'  #ID'name': 'DryBar'

limit= 15

url= 'https://api.foursquare.com/v2/venues/{}?client_id={}&client_secret={}&oauth_token={}&v={}'.format(
    venue_id, CLIENT_ID, CLIENT_SECRET,ACCESS_TOKEN, VERSION,limit)

results= requests.get(url).json()

print("O ID:" ,results["response"]["venue"]["likes"]["count"])

O ID: 18

In [37]:
venue_id = lista_id 

for results in venue_id:
    
    limit= 15
    url= 'https://api.foursquare.com/v2/venues/{}?client_id={}&client_secret={}&oauth_token={}&v={}'.format(
        venue_id, CLIENT_ID, CLIENT_SECRET,ACCESS_TOKEN, VERSION,limit)
    results= requests.get(url).json()
    results=results["response"]["venue"]["likes"]["count"]

    print(results)

KeyError: 'venue'

# paulo me ajuda a entender o que são 11?

In [244]:
results['response']['venue']['tips']['items'][0]["user"]["id"]

KeyError: 'items'

In [241]:
results['response']['venue']["tips"]

{'count': 11,
 'groups': [{'type': 'following',
   'name': 'Tips from people you follow',
   'count': 0,
   'items': []},
  {'type': 'others',
   'name': 'All tips',
   'count': 11,
   'items': [{'id': '5113f702e4b006dae5710f94',
     'createdAt': 1360262914,
     'text': "If you want big curls & big volume (The Southern Comfort), ask for Lisaundra Garcia and you will get exactly what you desire. She's wonderful, as is Drybar!",
     'type': 'user',
     'canonicalUrl': 'https://foursquare.com/item/5113f702e4b006dae5710f94',
     'likes': {'count': 2,
      'groups': [{'type': 'others',
        'count': 2,
        'items': [{'id': '1578437',
          'firstName': 'LeAura',
          'lastName': 'L',
          'gender': 'female',
          'countryCode': 'US',
          'photo': {'prefix': 'https://fastly.4sqi.net/img/user/',
           'suffix': '/TOLNPICIVLYGLZJ5.jpg'}},
         {'id': '3214993',
          'firstName': 'Shauna',
          'lastName': 'Shepston',
          'gender': 'female',
          'countryCode': 'US',
          'photo': {'prefix': 'https://fastly.4sqi.net/img/user/',
           'suffix': '/3214993-OIMTPUKTFLUDKF5F.jpg'}}]}],
      'summary': '2 likes'},
     'like': False,
     'logView': True,
     'agreeCount': 3,
     'disagreeCount': 0,
     'todo': {'count': 0},
     'user': {'id': '3147254',
      'firstName': 'Katie',
      'lastName': 'S.',
      'gender': 'female',
      'countryCode': 'US',
      'photo': {'prefix': 'https://fastly.4sqi.net/img/user/',
       'suffix': '/KPK0SB20U3D4451L.jpg'}}}]}]}

### Transformar em data frame

In [240]:
tip_df = json_normalize(se) # json normalize tips
tip_df

,count,groups
0,11,"[{'type': 'following', 'name': 'Tips from people you follow', 'count': 0, 'items': []}, {'type': 'others', 'name': 'All tips', 'count': 11, 'items': [{'id': '5113f702e4b006dae5710f94', 'createdAt': 1360262914, 'text': ""If you want big curls & big volume (The Southern Comfort), ask for Lisaundra Garcia and you will get exactly what you desire. She's wonderful, as is Drybar!"", 'type': 'user', 'canonicalUrl': 'https://foursquare.com/item/5113f702e4b006dae5710f94', 'likes': {'count': 2, 'groups': [{'type': 'others', 'count': 2, 'items': [{'id': '1578437', 'firstName': 'LeAura', 'lastName': 'L', 'gender': 'female', 'countryCode': 'US', 'photo': {'prefix': 'https://fastly.4sqi.net/img/user/', 'suffix': '/TOLNPICIVLYGLZJ5.jpg'}}, {'id': '3214993', 'firstName': 'Shauna', 'lastName': 'Shepston', 'gender': 'female', 'countryCode': 'US', 'photo': {'prefix': 'https://fastly.4sqi.net/img/user/', 'suffix': '/3214993-OIMTPUKTFLUDKF5F.jpg'}}]}], 'summary': '2 likes'}, 'like': False, 'logView': True, 'agreeCount': 3, 'disagreeCount': 0, 'todo': {'count': 0}, 'user': {'id': '3147254', 'firstName': 'Katie', 'lastName': 'S.', 'gender': 'female', 'countryCode': 'US', 'photo': {'prefix': 'https://fastly.4sqi.net/img/user/', 'suffix': '/KPK0SB20U3D4451L.jpg'}}}]}]"

In [172]:
tips2 = results_tip['response']['tips']['items']

tips_df2 = json_normalize(tips2) # json normalize tips

tips_df2

,id,createdAt,text,type,canonicalUrl,like,logView,agreeCount,disagreeCount,authorInteractionType,likes.count,likes.groups,todo.count,user.id,user.firstName,user.lastName,user.gender,user.countryCode,user.photo.prefix,user.photo.suffix
0,562086de498e766b24d1ca86,1444972254,"Newest New York location and despite being in a busy part of Midtown, it's still not as busy as some of the other locations so it's ideal for walk-ins still!",user,https://foursquare.com/item/562086de498e766b24d1ca86,False,True,0,0,liked,0,[],0,2955249,Nadia,IssaBella,female,CA,https://fastly.4sqi.net/img/user/,/2955249-LEHE5CUVGIFEF4GG.jpg

# Agora vou explorar o Id para chegar nas dicas

In [205]:
df_midtown.id
lista_id=df_midtown["id"]
lista_id.tolist()
lista_id

0     5345ddce498e374167fa7173
1     4f2064f8e4b0a00cf1d3c3c1
2     558e9564498e4c9557996706
3     4e6f679dae604d1b459a5154
4     5db77e4d10a19d000875e753
5     50df63efe4b0454c5e8f655d
6     59a4d46e61f0705add6bacf6
7     5085a8b5e4b0ca321fdcea32
8     565da01f498ef6985cb9a345
9     5085a82ce4b06b2e3c6b644b
10    581df4b5b04e9861eb58bf73
11    54ae7536498e4611855629f5
12    573ef3fd498e246fea9ae4b5
13    57732792498edf5509c6c020
14    5293c092498efb087b95ea2c
15    5b7d6c786fd626002c394614
16    5628e8f7498e5a2719912fb0
17    5a983849a5a3156b15012ff4
18    54943a62498eff4bb43d26b0
19    5675b3fa498eafd413130732
20    5b474e2c10b30300247c8a49
21    514b8985e4b080852ac00c85
22    57d34283498e5a4993a2eff7
23    58efd26867af3a2c5ae21e34
24    55354a66498e43895e540020
25    5546681f498e448ae1f7cc9d
26    5740c975498e39a5c6e1e6da
27    576ab85f498ea7d347c23267
28    51ccd28d498e8edf647e0d88
29    5a749b70e2d4aa45ead68c65
30    52ed381d498e515b85c74a27
31    57001738cd10a426c20ea3dd
32    58e96bf99c95484a51494b3e
33    587f9a323ef0f6426ea9fed4
34    5c6892aaf709c1002cba9699
35    59cbee67a0215b7fe38355a3
36    536d583b11d2f3547c412a94
37    5377f56611d245aa7ab39ce9
38    514c6d1580550268cdba3537
39    5db71016e370da000860a2c6
40    5bb0ef40e1f0aa002c3a5bfd
41    5634f740498eb62fdc1f9f3e
Name: id, dtype: object

In [203]:
venue_id = '4f2064f8e4b0a00cf1d3c3c1' # ID 'name': 'DryBar'

url_2 = 'https://api.foursquare.com/v2/venues/{}?client_id={}&client_secret={}&oauth_token={}&v={}'.format(
    venue_id, CLIENT_ID, CLIENT_SECRET,ACCESS_TOKEN, VERSION)

results= requests.get(url_2).json()

In [195]:
results_tip = requests.get(url_2).json()
results_tip['response'].keys()

dict_keys(['venue'])

In [192]:
results_tip['response']['tips']['items'][0]["user"]["id"]

KeyError: 'tips'

In [173]:
results_tip['response']['tips']['items'][0]["user"]["id"]

'2955249'

In [176]:
user_id='2955249'
url = 'https://api.foursquare.com/v2/users/{}/tips?client_id={}&client_secret={}&oauth_token={}&v={}&limit={}'.format(user_id, CLIENT_ID, CLIENT_SECRET,ACCESS_TOKEN,VERSION, limit)

# send GET request and get user's tips
results = requests.get(url).json()
tips = results_tip['response']['tips']['items']

# format column width
pd.set_option('display.max_colwidth', -1)

tips_df = json_normalize(tips)

# filter columns
filtered_columns = ['text', 'agreeCount', 'disagreeCount', 'id']
tips_filtered2 = tips_df.loc[:, filtered_columns]

# display user's tips
tips_filtered2

,text,agreeCount,disagreeCount,id
0,"Newest New York location and despite being in a busy part of Midtown, it's still not as busy as some of the other locations so it's ideal for walk-ins still!",0,0,562086de498e766b24d1ca86

In [114]:
results_2['response']['venue']["tips"]

{'count': 11,
 'groups': [{'type': 'following',
   'name': 'Tips from people you follow',
   'count': 0,
   'items': []},
  {'type': 'others',
   'name': 'All tips',
   'count': 11,
   'items': [{'id': '5520120c498eddc613071393',
     'createdAt': 1428165132,
     'text': "My favorite Dry Bar! The stylists know how to handle my big curly hair. Other places leave my hair dried and fried, but the stylists here use products to protect my hair. Haven't been disappointed yet",
     'type': 'user',
     'canonicalUrl': 'https://foursquare.com/item/5520120c498eddc613071393',
     'likes': {'count': 1,
      'groups': [{'type': 'others',
        'count': 1,
        'items': [{'id': '7880425',
          'firstName': 'Althea',
          'lastName': 'Smith',
          'gender': 'female',
          'countryCode': 'US',
          'photo': {'prefix': 'https://fastly.4sqi.net/img/user/',
           'suffix': '/7880425-KI011V3HTRVRNANG.jpg'}}]}],
      'summary': '1 like'},
     'like': False,
     'logView': True,
     'agreeCount': 1,
     'disagreeCount': 0,
     'todo': {'count': 0},
     'user': {'id': '2379147',
      'firstName': 'Ann',
      'lastName': 'Kettles',
      'gender': 'female',
      'countryCode': 'US',
      'photo': {'prefix': 'https://fastly.4sqi.net/img/user/',
       'suffix': '/TUN51RFFJJLG23W5.jpg'}}}]}]}

In [50]:
# dataframe 
One_venue=results_2['response']['venue']

One_df = json_normalize(t) # json normalize tips
One_df

,id,name,canonicalUrl,categories,verified,url,like,dislike,ok,rating,...,bestPhoto.prefix,bestPhoto.suffix,bestPhoto.width,bestPhoto.height,bestPhoto.visibility,colors.highlightColor.photoId,colors.highlightColor.value,colors.highlightTextColor.photoId,colors.highlightTextColor.value,colors.algoVersion
0,5345ddce498e374167fa7173,DryBar,https://foursquare.com/v/drybar/5345ddce498e374167fa7173,"[{'id': '4bf58dd8d48988d110951735', 'name': 'Salon / Barbershop', 'pluralName': 'Salons / Barbershops', 'shortName': 'Salon / Barbershop', 'icon': {'prefix': 'https://ss3.4sqi.net/img/categories_v2/shops/salon_barber_', 'suffix': '.png'}, 'primary': True}]",False,http://www.thedrybar.com,False,False,False,8.4,...,https://fastly.4sqi.net/img/general/,/14256689_j81S327y2JUwO4gjkW-9Z8104Sfp2q7tPd_Ov6SiZfA.jpg,975,1920,public,5d98afbd6b8567000807e97f,-2047880,5d98afbd6b8567000807e97f,-16777216,3

In [52]:
results_2['response']['venue'].keys()

dict_keys(['id', 'name', 'contact', 'location', 'canonicalUrl', 'categories', 'verified', 'stats', 'url', 'likes', 'like', 'dislike', 'ok', 'rating', 'ratingColor', 'ratingSignals', 'allowMenuUrlEdit', 'beenHere', 'specials', 'photos', 'reasons', 'hereNow', 'createdAt', 'tips', 'shortUrl', 'timeZone', 'listed', 'popular', 'seasonalHours', 'pageUpdates', 'inbox', 'attributes', 'bestPhoto', 'colors'])

In [82]:
print("Name:")
print("rating:",results_2['response']['venue']['rating'])
print("Likes:",results_2['response']['venue']['likes']['count'])
print("Text:","\n",results_2['response']['venue']['tips']['groups'][1]['items'][0]["text"])

Name:
rating: 8.4
Likes: 62
Text:
 My favorite Dry Bar! The stylists know how to handle my big curly hair. Other places leave my hair dried and fried, but the stylists here use products to protect my hair. Haven't been disappointed yet

In [107]:
results_2["response"]['venue'].keys()

dict_keys(['id', 'name', 'contact', 'location', 'canonicalUrl', 'categories', 'verified', 'stats', 'url', 'likes', 'like', 'dislike', 'ok', 'rating', 'ratingColor', 'ratingSignals', 'allowMenuUrlEdit', 'beenHere', 'specials', 'photos', 'reasons', 'hereNow', 'createdAt', 'tips', 'shortUrl', 'timeZone', 'listed', 'popular', 'seasonalHours', 'pageUpdates', 'inbox', 'attributes', 'bestPhoto', 'colors'])

In [110]:
results_2["response"]['venue']["tips"]

{'count': 11,
 'groups': [{'type': 'following',
   'name': 'Tips from people you follow',
   'count': 0,
   'items': []},
  {'type': 'others',
   'name': 'All tips',
   'count': 11,
   'items': [{'id': '5520120c498eddc613071393',
     'createdAt': 1428165132,
     'text': "My favorite Dry Bar! The stylists know how to handle my big curly hair. Other places leave my hair dried and fried, but the stylists here use products to protect my hair. Haven't been disappointed yet",
     'type': 'user',
     'canonicalUrl': 'https://foursquare.com/item/5520120c498eddc613071393',
     'likes': {'count': 1,
      'groups': [{'type': 'others',
        'count': 1,
        'items': [{'id': '7880425',
          'firstName': 'Althea',
          'lastName': 'Smith',
          'gender': 'female',
          'countryCode': 'US',
          'photo': {'prefix': 'https://fastly.4sqi.net/img/user/',
           'suffix': '/7880425-KI011V3HTRVRNANG.jpg'}}]}],
      'summary': '1 like'},
     'like': False,
     'logView': True,
     'agreeCount': 1,
     'disagreeCount': 0,
     'todo': {'count': 0},
     'user': {'id': '2379147',
      'firstName': 'Ann',
      'lastName': 'Kettles',
      'gender': 'female',
      'countryCode': 'US',
      'photo': {'prefix': 'https://fastly.4sqi.net/img/user/',
       'suffix': '/TUN51RFFJJLG23W5.jpg'}}}]}]}

In [103]:
# dataframe 2
Two_venue= results_2['response']['tips']['items']
Two_venue

KeyError: 'tips'

In [102]:

two_df = json_normalize(t) # json normalize tips
two_df

,id,name,canonicalUrl,categories,verified,url,like,dislike,ok,rating,...,bestPhoto.prefix,bestPhoto.suffix,bestPhoto.width,bestPhoto.height,bestPhoto.visibility,colors.highlightColor.photoId,colors.highlightColor.value,colors.highlightTextColor.photoId,colors.highlightTextColor.value,colors.algoVersion
0,5345ddce498e374167fa7173,DryBar,https://foursquare.com/v/drybar/5345ddce498e374167fa7173,"[{'id': '4bf58dd8d48988d110951735', 'name': 'Salon / Barbershop', 'pluralName': 'Salons / Barbershops', 'shortName': 'Salon / Barbershop', 'icon': {'prefix': 'https://ss3.4sqi.net/img/categories_v2/shops/salon_barber_', 'suffix': '.png'}, 'primary': True}]",False,http://www.thedrybar.com,False,False,False,8.4,...,https://fastly.4sqi.net/img/general/,/14256689_j81S327y2JUwO4gjkW-9Z8104Sfp2q7tPd_Ov6SiZfA.jpg,975,1920,public,5d98afbd6b8567000807e97f,-2047880,5d98afbd6b8567000807e97f,-16777216,3

In [95]:
results_2['response']['venue']["tips"]["groups"][1]['items'][0]

{'id': '5520120c498eddc613071393',
 'createdAt': 1428165132,
 'text': "My favorite Dry Bar! The stylists know how to handle my big curly hair. Other places leave my hair dried and fried, but the stylists here use products to protect my hair. Haven't been disappointed yet",
 'type': 'user',
 'canonicalUrl': 'https://foursquare.com/item/5520120c498eddc613071393',
 'likes': {'count': 1,
  'groups': [{'type': 'others',
    'count': 1,
    'items': [{'id': '7880425',
      'firstName': 'Althea',
      'lastName': 'Smith',
      'gender': 'female',
      'countryCode': 'US',
      'photo': {'prefix': 'https://fastly.4sqi.net/img/user/',
       'suffix': '/7880425-KI011V3HTRVRNANG.jpg'}}]}],
  'summary': '1 like'},
 'like': False,
 'logView': True,
 'agreeCount': 1,
 'disagreeCount': 0,
 'todo': {'count': 0},
 'user': {'id': '2379147',
  'firstName': 'Ann',
  'lastName': 'Kettles',
  'gender': 'female',
  'countryCode': 'US',
  'photo': {'prefix': 'https://fastly.4sqi.net/img/user/',
   'suffix': '/TUN51RFFJJLG23W5.jpg'}}}

In [31]:
print(results_2['response']['venue']["name"])
print()

'DryBar'

In [85]:
results_2['response']['venue']["tips"]["groups"][1]['photo']

KeyError: 'photo'

In [35]:
results_2['response']['venue']

{'id': '5345ddce498e374167fa7173',
 'name': 'DryBar',
 'contact': {},
 'location': {'address': '141 E 56th St',
  'crossStreet': '56th Street And Lexington Avenue',
  'lat': 40.76008684544023,
  'lng': -73.96912585199476,
  'labeledLatLngs': [{'label': 'display',
    'lat': 40.76008684544023,
    'lng': -73.96912585199476}],
  'postalCode': '10022',
  'cc': 'US',
  'city': 'New York',
  'state': 'NY',
  'country': 'United States',
  'formattedAddress': ['141 E 56th St (56th Street And Lexington Avenue)',
   'New York, NY 10022',
   'United States']},
 'canonicalUrl': 'https://foursquare.com/v/drybar/5345ddce498e374167fa7173',
 'categories': [{'id': '4bf58dd8d48988d110951735',
   'name': 'Salon / Barbershop',
   'pluralName': 'Salons / Barbershops',
   'shortName': 'Salon / Barbershop',
   'icon': {'prefix': 'https://ss3.4sqi.net/img/categories_v2/shops/salon_barber_',
    'suffix': '.png'},
   'primary': True}],
 'verified': False,
 'stats': {'tipCount': 11},
 'url': 'http://www.thedrybar.com',
 'likes': {'count': 62,
  'groups': [{'type': 'others', 'count': 62, 'items': []}],
  'summary': '62 Likes'},
 'like': False,
 'dislike': False,
 'ok': False,
 'rating': 8.4,
 'ratingColor': '73CF42',
 'ratingSignals': 79,
 'allowMenuUrlEdit': True,
 'beenHere': {'count': 0,
  'unconfirmedCount': 0,
  'marked': False,
  'lastCheckinExpiredAt': 0},
 'specials': {'count': 0, 'items': []},
 'photos': {'count': 19,
  'groups': [{'type': 'venue',
    'name': 'Venue photos',
    'count': 19,
    'items': [{'id': '5d98afbd6b8567000807e97f',
      'createdAt': 1570287549,
      'source': {'name': 'Swarm for iOS', 'url': 'https://www.swarmapp.com'},
      'prefix': 'https://fastly.4sqi.net/img/general/',
      'suffix': '/14256689_j81S327y2JUwO4gjkW-9Z8104Sfp2q7tPd_Ov6SiZfA.jpg',
      'width': 975,
      'height': 1920,
      'user': {'id': '14256689',
       'firstName': 'Hayley',
       'lastName': 'S',
       'gender': 'female',
       'countryCode': 'US',
       'photo': {'prefix': 'https://fastly.4sqi.net/img/user/',
        'suffix': '/14256689_snlz07Qh_d9AOa0s00xZW9sMyLozYEa65dAKTsngLT29nJQPRF4AiSryv1vXOmDLp8Ru8Pr6y.jpg'}},
      'visibility': 'public'}]}]},
 'reasons': {'count': 1,
  'items': [{'summary': 'Lots of people like this place',
    'type': 'general',
    'reasonName': 'rawLikesReason'}]},
 'hereNow': {'count': 0, 'summary': 'Nobody here', 'groups': []},
 'createdAt': 1397087694,
 'tips': {'count': 11,
  'groups': [{'type': 'following',
    'name': 'Tips from people you follow',
    'count': 0,
    'items': []},
   {'type': 'others',
    'name': 'All tips',
    'count': 11,
    'items': [{'id': '5520120c498eddc613071393',
      'createdAt': 1428165132,
      'text': "My favorite Dry Bar! The stylists know how to handle my big curly hair. Other places leave my hair dried and fried, but the stylists here use products to protect my hair. Haven't been disappointed yet",
      'type': 'user',
      'canonicalUrl': 'https://foursquare.com/item/5520120c498eddc613071393',
      'likes': {'count': 1,
       'groups': [{'type': 'others',
         'count': 1,
         'items': [{'id': '7880425',
           'firstName': 'Althea',
           'lastName': 'Smith',
           'gender': 'female',
           'countryCode': 'US',
           'photo': {'prefix': 'https://fastly.4sqi.net/img/user/',
            'suffix': '/7880425-KI011V3HTRVRNANG.jpg'}}]}],
       'summary': '1 like'},
      'like': False,
      'logView': True,
      'agreeCount': 1,
      'disagreeCount': 0,
      'todo': {'count': 0},
      'user': {'id': '2379147',
       'firstName': 'Ann',
       'lastName': 'Kettles',
       'gender': 'female',
       'countryCode': 'US',
       'photo': {'prefix': 'https://fastly.4sqi.net/img/user/',
        'suffix': '/TUN51RFFJJLG23W5.jpg'}}}]}]},
 'shortUrl': 'http://4sq.com/1mYuz6e',
 'timeZone': 'America/New_York',
 'listed': {'count': 4,
  'groups': [{'type': 'others',
    'name': 'Lists from other people',
    'count': 4,
    'items': [{'id': '5998f13d249623221b4b32b4',
      'name': 'New York',
      'description': '',
      'type': 'others',
      'user': {'id': '81431665',
       'firstName': 'Hania',
       'lastName': 'Almousa',
       'gender': 'female',
       'countryCode': 'SA',
       'photo': {'prefix': 'https://fastly.4sqi.net/img/user/',
        'suffix': '/81431665_qL-kaCTn_uk8j62AY2wkL5u3NNgIOGkeLx8Or8FWw7thI8MZfuxwJullRTaE69EnoqO3r2M7s.jpg'}},
      'editable': False,
      'public': True,
      'collaborative': False,
      'url': '/user/81431665/list/new-york',
      'canonicalUrl': 'https://foursquare.com/user/81431665/list/new-york',
      'createdAt': 1503195453,
      'updatedAt': 1504747347,
      'photo': {'id': '5776fc86498e9a080dca82d4',
       'createdAt': 1467415686,
       'prefix': 'https://fastly.4sqi.net/img/general/',
       'suffix': '/91136_L4bVcJgoWOVmmDHBfcxVG4fajemCpf9OttQhLKKE1Xw.jpg',
       'width': 1440,
       'height': 1440,
       'user': {'id': '91136',
        'firstName': 'Jeff',
        'lastName': 'Woo',
        'gender': 'male',
        'address': '',
        'city': '',
        'state': '',
        'countryCode': 'US',
        'photo': {'prefix': 'https://fastly.4sqi.net/img/user/',
         'suffix': '/91136_49RtiWri_jh71CktlUTFK0sJluTLGAKLwGvEIo7wvm7eAY5YRP6tGI0HLTKfWwE0rlGqZJBPh.jpg'}},
       'visibility': 'public'},
      'followers': {'count': 0},
      'listItems': {'count': 27,
       'items': [{'id': 'v5345ddce498e374167fa7173',
         'createdAt': 1503332191}]}},
     {'id': '5bdda23e237dee002c8224ef',
      'name': 'NYC',
      'description': '',
      'type': 'others',
      'user': {'id': '422639873',
       'firstName': '',
       'gender': 'none',
       'countryCode': 'HN',
       'photo': {'prefix': 'https://fastly.4sqi.net/img/user/',
        'suffix': '/blank_boy.png',
        'default': True}},
      'editable': False,
      'public': True,
      'collaborative': False,
      'url': '/user/422639873/list/nyc',
      'canonicalUrl': 'https://foursquare.com/user/422639873/list/nyc',
      'createdAt': 1541251646,
      'updatedAt': 1541961042,
      'photo': {'id': '599eb56fd0a149403a9deffe',
       'createdAt': 1503573359,
       'prefix': 'https://fastly.4sqi.net/img/general/',
       'suffix': '/17728180_ltqz5ic8j_0M2br6nmNMHJM2_nHUvRFMPI2V438BZh8.jpg',
       'width': 1440,
       'height': 1920,
       'user': {'id': '17728180',
        'firstName': 'Hessah',
        'gender': 'female',
        'countryCode': 'SA',
        'photo': {'prefix': 'https://fastly.4sqi.net/img/user/',
         'suffix': '/17728180_yvLz-Wry_ZIfExa55is9pQR0wl7ToYJkIgbkZMH_7vfi9ncLnXSXa7o0ruZfNaIN2upKdKueK.jpg'}},
       'visibility': 'public'},
      'followers': {'count': 0},
      'listItems': {'count': 26,
       'items': [{'id': 'v5345ddce498e374167fa7173',
         'createdAt': 1541252621}]}}]}]},
 'popular': {'status': 'Likely open',
  'richStatus': {'entities': [], 'text': 'Likely open'},
  'isOpen': True,
  'isLocalHoliday': False,
  'timeframes': [{'days': 'Today',
    'includesToday': True,
    'open': [{'renderedTime': '9:00 AM–Noon'},
     {'renderedTime': '2:00 PM–4:00 PM'}],
    'segments': []},
   {'days': 'Mon',
    'open': [{'renderedTime': '7:00 AM–11:00 AM'}],
    'segments': []},
   {'days': 'Tue',
    'open': [{'renderedTime': '7:00 AM–9:00 AM'},
     {'renderedTime': 'Noon–1:00 PM'},
     {'renderedTime': '4:00 PM–7:00 PM'}],
    'segments': []},
   {'days': 'Wed',
    'open': [{'renderedTime': '7:00 AM–7:00 PM'}],
    'segments': []},
   {'days': 'Thu',
    'open': [{'renderedTime': '7:00 AM–2:00 PM'},
     {'renderedTime': '4:00 PM–8:00 PM'}],
    'segments': []},
   {'days': 'Fri',
    'open': [{'renderedTime': '7:00 AM–8:00 PM'}],
    'segments': []},
   {'days': 'Sat',
    'open': [{'renderedTime': '8:00 AM–9:00 PM'}],
    'segments': []}]},
 'seasonalHours': [],
 'pageUpdates': {'count': 0, 'items': []},
 'inbox': {'count': 0, 'items': []},
 'attributes': {'groups': [{'type': 'payments',
    'name': 'Credit Cards',
    'summary': 'Credit Cards',
    'count': 7,
    'items': [{'displayName': 'Credit Cards', 'displayValue': 'Yes'}]}]},
 'bestPhoto': {'id': '5d98afbd6b8567000807e97f',
  'createdAt': 1570287549,
  'source': {'name': 'Swarm for iOS', 'url': 'https://www.swarmapp.com'},
  'prefix': 'https://fastly.4sqi.net/img/general/',
  'suffix': '/14256689_j81S327y2JUwO4gjkW-9Z8104Sfp2q7tPd_Ov6SiZfA.jpg',
  'width': 975,
  'height': 1920,
  'visibility': 'public'},
 'colors': {'highlightColor': {'photoId': '5d98afbd6b8567000807e97f',
   'value': -2047880},
  'highlightTextColor': {'photoId': '5d98afbd6b8567000807e97f',
   'value': -16777216},
  'algoVersion': 3}}

In [46]:
tips1=results_2['response']['venue']["tips"]["groups"][1]['items']

In [69]:
result['response']['venue']["photos"]

{'count': 19,
 'groups': [{'type': 'venue',
   'name': 'Venue photos',
   'count': 19,
   'items': [{'id': '5d98afbd6b8567000807e97f',
     'createdAt': 1570287549,
     'source': {'name': 'Swarm for iOS', 'url': 'https://www.swarmapp.com'},
     'prefix': 'https://fastly.4sqi.net/img/general/',
     'suffix': '/14256689_j81S327y2JUwO4gjkW-9Z8104Sfp2q7tPd_Ov6SiZfA.jpg',
     'width': 975,
     'height': 1920,
     'user': {'id': '14256689',
      'firstName': 'Hayley',
      'lastName': 'S',
      'gender': 'female',
      'countryCode': 'US',
      'photo': {'prefix': 'https://fastly.4sqi.net/img/user/',
       'suffix': '/14256689_snlz07Qh_d9AOa0s00xZW9sMyLozYEa65dAKTsngLT29nJQPRF4AiSryv1vXOmDLp8Ru8Pr6y.jpg'}},
     'visibility': 'public'}]}]}